import fs from "node:fs";

const DEPLOYS_FILE = "./scripts/deploy/deploys.json";
const MINTS_FILE = "./lib/mints.ts";

type DeployRecord = {
  id: string;
  symbol: string;
  mint: string;
  error?: string;
};

export type SyncResult = {
  written: number;
  failed: number;
};

export function writeMintsFile(): SyncResult {
  if (!fs.existsSync(DEPLOYS_FILE)) {
    return { written: 0, failed: 0 };
  }

  const deploys = JSON.parse(
    fs.readFileSync(DEPLOYS_FILE, "utf-8"),
  ) as Record<string, DeployRecord>;

  const successful = Object.values(deploys).filter((d) => !d.error);
  const failed = Object.values(deploys).filter((d) => d.error).length;

  // Hub first, then country ids alphabetically
  successful.sort((a, b) => {
    if (a.id === "hub") return -1;
    if (b.id === "hub") return 1;
    return a.id.localeCompare(b.id);
  });

  const lines: string[] = [
    "// Maps country.id (or \"hub\") to its deployed Solana mint address.",
    "// Auto-generated by scripts/deploy/sync-mints.ts (called after each successful deploy).",
    "// Re-run manually with: npm run deploy:sync",
    "export const MINTS: Record<string, string> = {",
  ];
  for (const d of successful) {
    lines.push(`  ${JSON.stringify(d.id)}: ${JSON.stringify(d.mint)},`);
  }
  lines.push("};");
  lines.push("");

  fs.writeFileSync(MINTS_FILE, lines.join("\n"), "utf-8");

  return { written: successful.length, failed };
}

function main() {
  const result = writeMintsFile();
  if (result.written === 0) {
    console.log(
      "No successful deploys in deploys.json — nothing to sync.",
    );
    return;
  }
  console.log(`✓ Wrote ${result.written} mints to ${MINTS_FILE}`);
  if (result.failed > 0) {
    console.log(
      `\nNote: ${result.failed} deploy(s) failed and were not written. Re-run 'npm run deploy' to retry.`,
    );
  }
}

if (process.argv[1]?.endsWith("sync-mints.ts")) {
  main();
}
