import fs from "node:fs";

const DEPLOYS_FILE = "./scripts/deploy/deploys.json";
const MINTS_FILE = "./lib/mints.ts";

type DeployRecord = {
  id: string;
  symbol: string;
  mint: string;
  error?: string;
};

function main() {
  if (!fs.existsSync(DEPLOYS_FILE)) {
    console.error(
      `${DEPLOYS_FILE} not found. Run 'npm run deploy' first.`,
    );
    process.exit(1);
  }

  const deploys = JSON.parse(
    fs.readFileSync(DEPLOYS_FILE, "utf-8"),
  ) as Record<string, DeployRecord>;

  const successful = Object.values(deploys).filter((d) => !d.error);
  if (successful.length === 0) {
    console.log("No successful deploys in deploys.json — nothing to sync.");
    return;
  }

  // Sort: hub first, then by id alphabetically
  successful.sort((a, b) => {
    if (a.id === "hub") return -1;
    if (b.id === "hub") return 1;
    return a.id.localeCompare(b.id);
  });

  const lines: string[] = [];
  lines.push("// Maps country.id (or \"hub\") to its deployed Solana mint address.");
  lines.push(
    "// Auto-generated by scripts/deploy/sync-mints.ts after each deploy run.",
  );
  lines.push("// To regenerate, run: npm run deploy:sync");
  lines.push("export const MINTS: Record<string, string> = {");
  for (const d of successful) {
    lines.push(`  ${JSON.stringify(d.id)}: ${JSON.stringify(d.mint)},`);
  }
  lines.push("};");
  lines.push("");

  fs.writeFileSync(MINTS_FILE, lines.join("\n"), "utf-8");
  console.log(`✓ Wrote ${successful.length} mints to ${MINTS_FILE}`);

  const failed = Object.values(deploys).filter((d) => d.error);
  if (failed.length > 0) {
    console.log(
      `\nNote: ${failed.length} deploy(s) failed and were not written. Re-run 'npm run deploy' to retry.`,
    );
    for (const f of failed) {
      console.log(`  ✗ ${f.symbol} — ${f.error?.slice(0, 100)}`);
    }
  }
}

main();
