import fs from "node:fs";

const ASSIGNMENTS_FILE = "./scripts/deploy/assignments.json";
const MINTS_FILE = "./lib/mints.ts";

type Assignment = {
  id: string;
  name: string;
  symbol: string;
  vanityFile: string;
  publicKey: string;
};

export type SyncResult = { written: number };

export function writeMintsFile(): SyncResult {
  if (!fs.existsSync(ASSIGNMENTS_FILE)) {
    return { written: 0 };
  }

  const assignments = JSON.parse(
    fs.readFileSync(ASSIGNMENTS_FILE, "utf-8"),
  ) as Assignment[];

  // Hub first, then country ids alphabetically
  const sorted = [...assignments].sort((a, b) => {
    if (a.id === "hub") return -1;
    if (b.id === "hub") return 1;
    return a.id.localeCompare(b.id);
  });

  const lines: string[] = [
    "// Maps country.id (or \"hub\") to its reserved Solana mint address.",
    "// All addresses are vanity keypairs ending in CUP, pre-allocated from",
    "// scripts/deploy/assignments.json BEFORE the on-chain deploys happen.",
    "// Auto-regenerated by scripts/deploy/sync-mints.ts.",
    "// Manual regen: npm run deploy:sync",
    "export const MINTS: Record<string, string> = {",
  ];
  for (const a of sorted) {
    lines.push(`  ${JSON.stringify(a.id)}: ${JSON.stringify(a.publicKey)},`);
  }
  lines.push("};");
  lines.push("");

  fs.writeFileSync(MINTS_FILE, lines.join("\n"), "utf-8");
  return { written: sorted.length };
}

function main() {
  const result = writeMintsFile();
  if (result.written === 0) {
    console.log(
      `No ${ASSIGNMENTS_FILE} found. Run 'npm run deploy:assignments' first.`,
    );
    process.exit(1);
  }
  console.log(`✓ Wrote ${result.written} mints to ${MINTS_FILE}`);
}

if (process.argv[1]?.endsWith("sync-mints.ts")) {
  main();
}
