// Maps country.id (or "hub") to its deployed Solana mint address.
// Auto-generated by scripts/deploy/sync-mints.ts after each deploy run.
// Entries are filled in as tokens are deployed via Launchlab.
export const MINTS: Record<string, string> = {
  // hub: "Yo...someAddressEndingInCUP",
  // brazil: "...",
  // argentina: "...",
};
